global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: micrometer
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ['host.docker.internal:1234']
